# Cross Validation 

In [10]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [11]:
data = pd.read_csv("updated_placement.csv")
data.head(3)

cgpa    package
0  9.75  68.493428
1  5.36  23.323471
2  5.65  27.795377

In [42]:
# now we check this data set max and min accuracy and we als disccusss diff kinds of cros validation her
x = data.iloc[:,:-1]
y = data["package"]

In [64]:
from sklearn.linear_model import LinearRegression

In [65]:
from sklearn.model_selection import cross_val_score,KFold

In [66]:
p = cross_val_score(LinearRegression(),x,y,cv=5) # cv mean how many types we want to train our model we also
# give leave p out and all these insted of number 

In [67]:
p

array([0.95095686, 0.92972444, 0.95475438, 0.93793448, 0.91725879])

In [68]:
p.sort()
p

array([0.91725879, 0.92972444, 0.93793448, 0.95095686, 0.95475438])

In [81]:
# if we want to give k_fold or any 
Kfold = KFold(n_splits= 10)
k = cross_val_score(LinearRegression(),x,y,cv= kfold) # cv mean how many types we want to train our model we also
# give leave p out and all these insted of number 
k.sort()
k

array([0.82672412, 0.82864523, 0.90194896, 0.91212741, 0.94336845,
       0.96437318, 0.96924722, 0.98758844, 0.9880241 , 0.99228348])

In [20]:
# now we tak eonly 10 data to understan better 
new_data = data.head(10)

In [21]:
x_new = new_data['cgpa']
y_new = new_data['package']

In [22]:
from sklearn.model_selection import LeaveOneOut,LeavePOut,KFold,StratifiedKFold # on register explian 

# leave_one_out

In [23]:
lo = LeaveOneOut()
# to add data we used split data which considers data in it we iterate the data in it using loop 
for train,test in lo.split(x_new,y_new): # we used lo method to split our data 
    print(train,test)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


# leave_p_out

In [26]:
lp = LeavePOut(p=2)
# to add data we used split data which considers data in it we iterate the data in it using loop 
for train,test in lp.split(x_new,y_new): # we used lo method to split our data 
    print(train,test)

[2 3 4 5 6 7 8 9] [0 1]
[1 3 4 5 6 7 8 9] [0 2]
[1 2 4 5 6 7 8 9] [0 3]
[1 2 3 5 6 7 8 9] [0 4]
[1 2 3 4 6 7 8 9] [0 5]
[1 2 3 4 5 7 8 9] [0 6]
[1 2 3 4 5 6 8 9] [0 7]
[1 2 3 4 5 6 7 9] [0 8]
[1 2 3 4 5 6 7 8] [0 9]
[0 3 4 5 6 7 8 9] [1 2]
[0 2 4 5 6 7 8 9] [1 3]
[0 2 3 5 6 7 8 9] [1 4]
[0 2 3 4 6 7 8 9] [1 5]
[0 2 3 4 5 7 8 9] [1 6]
[0 2 3 4 5 6 8 9] [1 7]
[0 2 3 4 5 6 7 9] [1 8]
[0 2 3 4 5 6 7 8] [1 9]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 3 5 6 7 8 9] [2 4]
[0 1 3 4 6 7 8 9] [2 5]
[0 1 3 4 5 7 8 9] [2 6]
[0 1 3 4 5 6 8 9] [2 7]
[0 1 3 4 5 6 7 9] [2 8]
[0 1 3 4 5 6 7 8] [2 9]
[0 1 2 5 6 7 8 9] [3 4]
[0 1 2 4 6 7 8 9] [3 5]
[0 1 2 4 5 7 8 9] [3 6]
[0 1 2 4 5 6 8 9] [3 7]
[0 1 2 4 5 6 7 9] [3 8]
[0 1 2 4 5 6 7 8] [3 9]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 5 7 8 9] [4 6]
[0 1 2 3 5 6 8 9] [4 7]
[0 1 2 3 5 6 7 9] [4 8]
[0 1 2 3 5 6 7 8] [4 9]
[0 1 2 3 4 7 8 9] [5 6]
[0 1 2 3 4 6 8 9] [5 7]
[0 1 2 3 4 6 7 9] [5 8]
[0 1 2 3 4 6 7 8] [5 9]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 7 9] [6 8]
[0 1 2 3 4 5 7 8

# k_fold

In [32]:
kf = KFold(n_splits=5)# n_splites mean in how many parts you want to break explain on register 
# to add data we used split data which considers data in it we iterate the data in it using loop 
for train,test in kf.split(x_new,y_new): # we used lo method to split our data 
    print(train,test)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


# satisfied_k_fold

In [34]:
sk = StratifiedKFold(n_splits=5)
# to add data we used split data which considers data in it we iterate the data in it using loop 
for train,test in sk.split(x_new,y_new): # we used lo method to split our data 
    print(train,test)

ValueError: Supported target types are: ('binary', 'multiclass'). Got 'continuous' instead.