# Techiques to handle it 

In [170]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [171]:
data = pd.read_csv("networkadds.csv")
data.head(3)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0

In [172]:
data1 = data.drop(columns=["User ID","Gender"])

In [173]:
data1["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [174]:
# MEANS There is an inbalancing inthe data set and our model is bias on 0 

In [175]:
x = data1.iloc[:,:-1]
y = data1["Purchased"]

In [176]:
from sklearn.model_selection import train_test_split

In [177]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.2,random_state=42)

In [178]:
from sklearn.linear_model import LogisticRegression

In [179]:
lr = LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [180]:
lr.score(x_test,y_test)*100

84.0625

In [204]:
lr.predict([[46,48000]])

C:\Users\R c\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [181]:
lr.predict([[45,26000]])

C:\Users\R c\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [182]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [183]:
data = pd.read_csv("networkadds.csv")

In [184]:
data1 = data.drop(columns=["User ID","Gender"])

In [185]:
x = data1.iloc[:,:-1]
y = data1["Purchased"]

In [186]:
data1["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [187]:
from imblearn.under_sampling import RandomUnderSampler

In [205]:
from imblearn.over_sampling import RandomOverSampler # first go down and read under sampling 

In [206]:
ro = RandomOverSampler()

In [208]:
ro_x,ro_y = ro.fit_resample(x,y)

In [212]:
ro_y.value_counts() # it repeats the values randomly 

Purchased
0    257
1    257
Name: count, dtype: int64

In [209]:
from sklearn.model_selection import train_test_split

In [210]:
x_train,x_test,y_train,y_test = train_test_split(ro_x,ro_y,train_size=0.2,random_state=42)

In [211]:
from sklearn.linear_model import LogisticRegression

In [213]:
lr.fit(x_train,y_train)

LogisticRegression()

In [215]:
lr.score(x_test,y_test)

0.837378640776699

In [216]:
lr.predict([[46,48000]]) # see it gives 1 accurate

C:\Users\R c\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

In [217]:
lr.predict([[32,150000]]) # more accurate then above

C:\Users\R c\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

In [218]:
lr.predict([[19,19000]]) # accurate 

C:\Users\R c\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [219]:
lr.predict([[19,21000]]) # accurate 

C:\Users\R c\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [220]:
ru_x,ru_y = ru.fit_resample(x,y) 

In [221]:
ru_x

Age  EstimatedSalary
199   35            22000
112   38            61000
100   27            88000
175   23            28000
353   37            57000
..   ...              ...
393   60            42000
395   46            41000
396   51            23000
397   50            20000
399   49            36000

[286 rows x 2 columns]

In [222]:
ru_y

199    0
112    0
100    0
175    0
353    0
      ..
393    1
395    1
396    1
397    1
399    1
Name: Purchased, Length: 286, dtype: int64

In [223]:
# now chek vlues are sep or not 

In [224]:
ru_y.value_counts()

Purchased
0    143
1    143
Name: count, dtype: int64

In [225]:
from sklearn.model_selection import train_test_split

In [226]:
x_train,x_test,y_train,y_test = train_test_split(ru_x,ru_y,train_size=0.2,random_state=42)

In [227]:
from sklearn.linear_model import LogisticRegression

In [228]:
lr1 = LogisticRegression()

In [229]:
lr1.fit(x_train,y_train)

LogisticRegression()

In [230]:
lr1.score(x_test,y_test)

0.8296943231441049

In [231]:
# so our score is decreased now check model accuracy improves or not 

In [232]:
lr1.predict([[19,19000]]) # now it gives the output 1 of max  and 0 on 0 


C:\Users\R c\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [233]:
lr1.predict([[46,48000]]) # on above it gives 0 now 1 which is according to the requirement 

C:\Users\R c\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

In [234]:
lr.predict([[46,48000]]) # see it gives 1 accurate

C:\Users\R c\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

In [235]:
lr.predict([[32,150000]]) # more accurate then above

C:\Users\R c\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])